### ISSUE TITLE
Doesn’t end Recordings after 12

### ISSUE THREAD

**Issue by VilterPD** [gras64/wake-word-skill#1]
Keeps recording for wake words indefinitely

**Comment by VilterPD** [comment]
I can only stop it by unplugging

**Comment by gras64** [comment]
when you speak, don't just say the wakeword but stop.Pay attention to the latest version

**Comment by VilterPD** [comment]
That seems to work, thank you 😊 still not reacting to the wake word, but some testing will resolve that 😊

**Comment by gras64** [comment]
i actually found a problem and made an update. try again.

**Comment by VilterPD** [comment]
Thanks 😊 and thank you for this awesome fuction

—————————
Gesendet von Philipp Därr

**Comment by gras64** [comment]
check out the forum https://community.mycroft.ai/t/wake-word-skill-trainer/7124/18 what's new.
